// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// EntryServiceUpdateReader is a Reader for the EntryServiceUpdate structure.
type EntryServiceUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EntryServiceUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEntryServiceUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEntryServiceUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEntryServiceUpdateOK creates a EntryServiceUpdateOK with default headers values
func NewEntryServiceUpdateOK() *EntryServiceUpdateOK {
	return &EntryServiceUpdateOK{}
}

/*EntryServiceUpdateOK handles this case with default header values.

A successful response.
*/
type EntryServiceUpdateOK struct {
	Payload *models.APIEntryResponse
}

func (o *EntryServiceUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/entry/{id}][%d] entryServiceUpdateOK  %+v", 200, o.Payload)
}

func (o *EntryServiceUpdateOK) GetPayload() *models.APIEntryResponse {
	return o.Payload
}

func (o *EntryServiceUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIEntryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEntryServiceUpdateDefault creates a EntryServiceUpdateDefault with default headers values
func NewEntryServiceUpdateDefault(code int) *EntryServiceUpdateDefault {
	return &EntryServiceUpdateDefault{
		_statusCode: code,
	}
}

/*EntryServiceUpdateDefault handles this case with default header values.

An unexpected error response.
*/
type EntryServiceUpdateDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the entry service update default response
func (o *EntryServiceUpdateDefault) Code() int {
	return o._statusCode
}

func (o *EntryServiceUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/entry/{id}][%d] EntryService_Update default  %+v", o._statusCode, o.Payload)
}

func (o *EntryServiceUpdateDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *EntryServiceUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
