// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEntryServiceDeleteParams creates a new EntryServiceDeleteParams object
// with the default values initialized.
func NewEntryServiceDeleteParams() *EntryServiceDeleteParams {
	var ()
	return &EntryServiceDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEntryServiceDeleteParamsWithTimeout creates a new EntryServiceDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEntryServiceDeleteParamsWithTimeout(timeout time.Duration) *EntryServiceDeleteParams {
	var ()
	return &EntryServiceDeleteParams{

		timeout: timeout,
	}
}

// NewEntryServiceDeleteParamsWithContext creates a new EntryServiceDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewEntryServiceDeleteParamsWithContext(ctx context.Context) *EntryServiceDeleteParams {
	var ()
	return &EntryServiceDeleteParams{

		Context: ctx,
	}
}

// NewEntryServiceDeleteParamsWithHTTPClient creates a new EntryServiceDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEntryServiceDeleteParamsWithHTTPClient(client *http.Client) *EntryServiceDeleteParams {
	var ()
	return &EntryServiceDeleteParams{
		HTTPClient: client,
	}
}

/*EntryServiceDeleteParams contains all the parameters to send to the API endpoint
for the entry service delete operation typically these are written to a http.Request
*/
type EntryServiceDeleteParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the entry service delete params
func (o *EntryServiceDeleteParams) WithTimeout(timeout time.Duration) *EntryServiceDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the entry service delete params
func (o *EntryServiceDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the entry service delete params
func (o *EntryServiceDeleteParams) WithContext(ctx context.Context) *EntryServiceDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the entry service delete params
func (o *EntryServiceDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the entry service delete params
func (o *EntryServiceDeleteParams) WithHTTPClient(client *http.Client) *EntryServiceDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the entry service delete params
func (o *EntryServiceDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the entry service delete params
func (o *EntryServiceDeleteParams) WithID(id string) *EntryServiceDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the entry service delete params
func (o *EntryServiceDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EntryServiceDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
