// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewFormatScoreServiceUpdateParams creates a new FormatScoreServiceUpdateParams object
// with the default values initialized.
func NewFormatScoreServiceUpdateParams() *FormatScoreServiceUpdateParams {
	var ()
	return &FormatScoreServiceUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFormatScoreServiceUpdateParamsWithTimeout creates a new FormatScoreServiceUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFormatScoreServiceUpdateParamsWithTimeout(timeout time.Duration) *FormatScoreServiceUpdateParams {
	var ()
	return &FormatScoreServiceUpdateParams{

		timeout: timeout,
	}
}

// NewFormatScoreServiceUpdateParamsWithContext creates a new FormatScoreServiceUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewFormatScoreServiceUpdateParamsWithContext(ctx context.Context) *FormatScoreServiceUpdateParams {
	var ()
	return &FormatScoreServiceUpdateParams{

		Context: ctx,
	}
}

// NewFormatScoreServiceUpdateParamsWithHTTPClient creates a new FormatScoreServiceUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFormatScoreServiceUpdateParamsWithHTTPClient(client *http.Client) *FormatScoreServiceUpdateParams {
	var ()
	return &FormatScoreServiceUpdateParams{
		HTTPClient: client,
	}
}

/*FormatScoreServiceUpdateParams contains all the parameters to send to the API endpoint
for the format score service update operation typically these are written to a http.Request
*/
type FormatScoreServiceUpdateParams struct {

	/*Body*/
	Body *models.APIFormatScoreRequestBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the format score service update params
func (o *FormatScoreServiceUpdateParams) WithTimeout(timeout time.Duration) *FormatScoreServiceUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the format score service update params
func (o *FormatScoreServiceUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the format score service update params
func (o *FormatScoreServiceUpdateParams) WithContext(ctx context.Context) *FormatScoreServiceUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the format score service update params
func (o *FormatScoreServiceUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the format score service update params
func (o *FormatScoreServiceUpdateParams) WithHTTPClient(client *http.Client) *FormatScoreServiceUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the format score service update params
func (o *FormatScoreServiceUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the format score service update params
func (o *FormatScoreServiceUpdateParams) WithBody(body *models.APIFormatScoreRequestBody) *FormatScoreServiceUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the format score service update params
func (o *FormatScoreServiceUpdateParams) SetBody(body *models.APIFormatScoreRequestBody) {
	o.Body = body
}

// WithID adds the id to the format score service update params
func (o *FormatScoreServiceUpdateParams) WithID(id string) *FormatScoreServiceUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the format score service update params
func (o *FormatScoreServiceUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FormatScoreServiceUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
