// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// FormatSeriesServiceViewReader is a Reader for the FormatSeriesServiceView structure.
type FormatSeriesServiceViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FormatSeriesServiceViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFormatSeriesServiceViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFormatSeriesServiceViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFormatSeriesServiceViewOK creates a FormatSeriesServiceViewOK with default headers values
func NewFormatSeriesServiceViewOK() *FormatSeriesServiceViewOK {
	return &FormatSeriesServiceViewOK{}
}

/*FormatSeriesServiceViewOK handles this case with default header values.

A successful response.
*/
type FormatSeriesServiceViewOK struct {
	Payload *models.APIFormatSeriesResponse
}

func (o *FormatSeriesServiceViewOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/format/series/{id}][%d] formatSeriesServiceViewOK  %+v", 200, o.Payload)
}

func (o *FormatSeriesServiceViewOK) GetPayload() *models.APIFormatSeriesResponse {
	return o.Payload
}

func (o *FormatSeriesServiceViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIFormatSeriesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFormatSeriesServiceViewDefault creates a FormatSeriesServiceViewDefault with default headers values
func NewFormatSeriesServiceViewDefault(code int) *FormatSeriesServiceViewDefault {
	return &FormatSeriesServiceViewDefault{
		_statusCode: code,
	}
}

/*FormatSeriesServiceViewDefault handles this case with default header values.

An unexpected error response.
*/
type FormatSeriesServiceViewDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the format series service view default response
func (o *FormatSeriesServiceViewDefault) Code() int {
	return o._statusCode
}

func (o *FormatSeriesServiceViewDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/format/series/{id}][%d] FormatSeriesService_View default  %+v", o._statusCode, o.Payload)
}

func (o *FormatSeriesServiceViewDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *FormatSeriesServiceViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
