// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// FormatScoreServiceDeleteReader is a Reader for the FormatScoreServiceDelete structure.
type FormatScoreServiceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FormatScoreServiceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFormatScoreServiceDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFormatScoreServiceDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFormatScoreServiceDeleteOK creates a FormatScoreServiceDeleteOK with default headers values
func NewFormatScoreServiceDeleteOK() *FormatScoreServiceDeleteOK {
	return &FormatScoreServiceDeleteOK{}
}

/*FormatScoreServiceDeleteOK handles this case with default header values.

A successful response.
*/
type FormatScoreServiceDeleteOK struct {
	Payload models.APIEmpty
}

func (o *FormatScoreServiceDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/format/score/{id}][%d] formatScoreServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *FormatScoreServiceDeleteOK) GetPayload() models.APIEmpty {
	return o.Payload
}

func (o *FormatScoreServiceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFormatScoreServiceDeleteDefault creates a FormatScoreServiceDeleteDefault with default headers values
func NewFormatScoreServiceDeleteDefault(code int) *FormatScoreServiceDeleteDefault {
	return &FormatScoreServiceDeleteDefault{
		_statusCode: code,
	}
}

/*FormatScoreServiceDeleteDefault handles this case with default header values.

An unexpected error response.
*/
type FormatScoreServiceDeleteDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the format score service delete default response
func (o *FormatScoreServiceDeleteDefault) Code() int {
	return o._statusCode
}

func (o *FormatScoreServiceDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/format/score/{id}][%d] FormatScoreService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *FormatScoreServiceDeleteDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *FormatScoreServiceDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
