// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// FormatScoreServiceViewReader is a Reader for the FormatScoreServiceView structure.
type FormatScoreServiceViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FormatScoreServiceViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFormatScoreServiceViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFormatScoreServiceViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFormatScoreServiceViewOK creates a FormatScoreServiceViewOK with default headers values
func NewFormatScoreServiceViewOK() *FormatScoreServiceViewOK {
	return &FormatScoreServiceViewOK{}
}

/*FormatScoreServiceViewOK handles this case with default header values.

A successful response.
*/
type FormatScoreServiceViewOK struct {
	Payload *models.APIFormatScoreResponse
}

func (o *FormatScoreServiceViewOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/format/score/{id}][%d] formatScoreServiceViewOK  %+v", 200, o.Payload)
}

func (o *FormatScoreServiceViewOK) GetPayload() *models.APIFormatScoreResponse {
	return o.Payload
}

func (o *FormatScoreServiceViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIFormatScoreResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFormatScoreServiceViewDefault creates a FormatScoreServiceViewDefault with default headers values
func NewFormatScoreServiceViewDefault(code int) *FormatScoreServiceViewDefault {
	return &FormatScoreServiceViewDefault{
		_statusCode: code,
	}
}

/*FormatScoreServiceViewDefault handles this case with default header values.

An unexpected error response.
*/
type FormatScoreServiceViewDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the format score service view default response
func (o *FormatScoreServiceViewDefault) Code() int {
	return o._statusCode
}

func (o *FormatScoreServiceViewDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/format/score/{id}][%d] FormatScoreService_View default  %+v", o._statusCode, o.Payload)
}

func (o *FormatScoreServiceViewDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *FormatScoreServiceViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
