// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// GameServiceQueryReader is a Reader for the GameServiceQuery structure.
type GameServiceQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GameServiceQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGameServiceQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGameServiceQueryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGameServiceQueryOK creates a GameServiceQueryOK with default headers values
func NewGameServiceQueryOK() *GameServiceQueryOK {
	return &GameServiceQueryOK{}
}

/*GameServiceQueryOK handles this case with default header values.

A successful response.
*/
type GameServiceQueryOK struct {
	Payload *models.APIGameResponseList
}

func (o *GameServiceQueryOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/game/query][%d] gameServiceQueryOK  %+v", 200, o.Payload)
}

func (o *GameServiceQueryOK) GetPayload() *models.APIGameResponseList {
	return o.Payload
}

func (o *GameServiceQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGameResponseList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGameServiceQueryDefault creates a GameServiceQueryDefault with default headers values
func NewGameServiceQueryDefault(code int) *GameServiceQueryDefault {
	return &GameServiceQueryDefault{
		_statusCode: code,
	}
}

/*GameServiceQueryDefault handles this case with default header values.

An unexpected error response.
*/
type GameServiceQueryDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the game service query default response
func (o *GameServiceQueryDefault) Code() int {
	return o._statusCode
}

func (o *GameServiceQueryDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/game/query][%d] GameService_Query default  %+v", o._statusCode, o.Payload)
}

func (o *GameServiceQueryDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *GameServiceQueryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
