// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// GroupServiceQueryReader is a Reader for the GroupServiceQuery structure.
type GroupServiceQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupServiceQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupServiceQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGroupServiceQueryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGroupServiceQueryOK creates a GroupServiceQueryOK with default headers values
func NewGroupServiceQueryOK() *GroupServiceQueryOK {
	return &GroupServiceQueryOK{}
}

/*GroupServiceQueryOK handles this case with default header values.

A successful response.
*/
type GroupServiceQueryOK struct {
	Payload *models.APIGroupResponseList
}

func (o *GroupServiceQueryOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/group/query][%d] groupServiceQueryOK  %+v", 200, o.Payload)
}

func (o *GroupServiceQueryOK) GetPayload() *models.APIGroupResponseList {
	return o.Payload
}

func (o *GroupServiceQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGroupResponseList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupServiceQueryDefault creates a GroupServiceQueryDefault with default headers values
func NewGroupServiceQueryDefault(code int) *GroupServiceQueryDefault {
	return &GroupServiceQueryDefault{
		_statusCode: code,
	}
}

/*GroupServiceQueryDefault handles this case with default header values.

An unexpected error response.
*/
type GroupServiceQueryDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the group service query default response
func (o *GroupServiceQueryDefault) Code() int {
	return o._statusCode
}

func (o *GroupServiceQueryDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/group/query][%d] GroupService_Query default  %+v", o._statusCode, o.Payload)
}

func (o *GroupServiceQueryDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *GroupServiceQueryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
