// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// GroupServiceComputeReader is a Reader for the GroupServiceCompute structure.
type GroupServiceComputeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupServiceComputeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupServiceComputeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGroupServiceComputeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGroupServiceComputeOK creates a GroupServiceComputeOK with default headers values
func NewGroupServiceComputeOK() *GroupServiceComputeOK {
	return &GroupServiceComputeOK{}
}

/*GroupServiceComputeOK handles this case with default header values.

A successful response.
*/
type GroupServiceComputeOK struct {
	Payload *models.APIGroupResponse
}

func (o *GroupServiceComputeOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/group/compute][%d] groupServiceComputeOK  %+v", 200, o.Payload)
}

func (o *GroupServiceComputeOK) GetPayload() *models.APIGroupResponse {
	return o.Payload
}

func (o *GroupServiceComputeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupServiceComputeDefault creates a GroupServiceComputeDefault with default headers values
func NewGroupServiceComputeDefault(code int) *GroupServiceComputeDefault {
	return &GroupServiceComputeDefault{
		_statusCode: code,
	}
}

/*GroupServiceComputeDefault handles this case with default header values.

An unexpected error response.
*/
type GroupServiceComputeDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the group service compute default response
func (o *GroupServiceComputeDefault) Code() int {
	return o._statusCode
}

func (o *GroupServiceComputeDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/group/compute][%d] GroupService_Compute default  %+v", o._statusCode, o.Payload)
}

func (o *GroupServiceComputeDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *GroupServiceComputeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
