// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewGroupServiceComputeParams creates a new GroupServiceComputeParams object
// with the default values initialized.
func NewGroupServiceComputeParams() *GroupServiceComputeParams {
	var ()
	return &GroupServiceComputeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGroupServiceComputeParamsWithTimeout creates a new GroupServiceComputeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGroupServiceComputeParamsWithTimeout(timeout time.Duration) *GroupServiceComputeParams {
	var ()
	return &GroupServiceComputeParams{

		timeout: timeout,
	}
}

// NewGroupServiceComputeParamsWithContext creates a new GroupServiceComputeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGroupServiceComputeParamsWithContext(ctx context.Context) *GroupServiceComputeParams {
	var ()
	return &GroupServiceComputeParams{

		Context: ctx,
	}
}

// NewGroupServiceComputeParamsWithHTTPClient creates a new GroupServiceComputeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGroupServiceComputeParamsWithHTTPClient(client *http.Client) *GroupServiceComputeParams {
	var ()
	return &GroupServiceComputeParams{
		HTTPClient: client,
	}
}

/*GroupServiceComputeParams contains all the parameters to send to the API endpoint
for the group service compute operation typically these are written to a http.Request
*/
type GroupServiceComputeParams struct {

	/*Body*/
	Body *models.APIID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the group service compute params
func (o *GroupServiceComputeParams) WithTimeout(timeout time.Duration) *GroupServiceComputeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group service compute params
func (o *GroupServiceComputeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group service compute params
func (o *GroupServiceComputeParams) WithContext(ctx context.Context) *GroupServiceComputeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group service compute params
func (o *GroupServiceComputeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group service compute params
func (o *GroupServiceComputeParams) WithHTTPClient(client *http.Client) *GroupServiceComputeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group service compute params
func (o *GroupServiceComputeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the group service compute params
func (o *GroupServiceComputeParams) WithBody(body *models.APIID) *GroupServiceComputeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the group service compute params
func (o *GroupServiceComputeParams) SetBody(body *models.APIID) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GroupServiceComputeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
