// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewRoundServiceComputeParams creates a new RoundServiceComputeParams object
// with the default values initialized.
func NewRoundServiceComputeParams() *RoundServiceComputeParams {
	var ()
	return &RoundServiceComputeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRoundServiceComputeParamsWithTimeout creates a new RoundServiceComputeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRoundServiceComputeParamsWithTimeout(timeout time.Duration) *RoundServiceComputeParams {
	var ()
	return &RoundServiceComputeParams{

		timeout: timeout,
	}
}

// NewRoundServiceComputeParamsWithContext creates a new RoundServiceComputeParams object
// with the default values initialized, and the ability to set a context for a request
func NewRoundServiceComputeParamsWithContext(ctx context.Context) *RoundServiceComputeParams {
	var ()
	return &RoundServiceComputeParams{

		Context: ctx,
	}
}

// NewRoundServiceComputeParamsWithHTTPClient creates a new RoundServiceComputeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRoundServiceComputeParamsWithHTTPClient(client *http.Client) *RoundServiceComputeParams {
	var ()
	return &RoundServiceComputeParams{
		HTTPClient: client,
	}
}

/*RoundServiceComputeParams contains all the parameters to send to the API endpoint
for the round service compute operation typically these are written to a http.Request
*/
type RoundServiceComputeParams struct {

	/*Body*/
	Body *models.APIID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the round service compute params
func (o *RoundServiceComputeParams) WithTimeout(timeout time.Duration) *RoundServiceComputeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the round service compute params
func (o *RoundServiceComputeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the round service compute params
func (o *RoundServiceComputeParams) WithContext(ctx context.Context) *RoundServiceComputeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the round service compute params
func (o *RoundServiceComputeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the round service compute params
func (o *RoundServiceComputeParams) WithHTTPClient(client *http.Client) *RoundServiceComputeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the round service compute params
func (o *RoundServiceComputeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the round service compute params
func (o *RoundServiceComputeParams) WithBody(body *models.APIID) *RoundServiceComputeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the round service compute params
func (o *RoundServiceComputeParams) SetBody(body *models.APIID) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RoundServiceComputeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
