// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRoundServiceViewParams creates a new RoundServiceViewParams object
// with the default values initialized.
func NewRoundServiceViewParams() *RoundServiceViewParams {
	var ()
	return &RoundServiceViewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRoundServiceViewParamsWithTimeout creates a new RoundServiceViewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRoundServiceViewParamsWithTimeout(timeout time.Duration) *RoundServiceViewParams {
	var ()
	return &RoundServiceViewParams{

		timeout: timeout,
	}
}

// NewRoundServiceViewParamsWithContext creates a new RoundServiceViewParams object
// with the default values initialized, and the ability to set a context for a request
func NewRoundServiceViewParamsWithContext(ctx context.Context) *RoundServiceViewParams {
	var ()
	return &RoundServiceViewParams{

		Context: ctx,
	}
}

// NewRoundServiceViewParamsWithHTTPClient creates a new RoundServiceViewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRoundServiceViewParamsWithHTTPClient(client *http.Client) *RoundServiceViewParams {
	var ()
	return &RoundServiceViewParams{
		HTTPClient: client,
	}
}

/*RoundServiceViewParams contains all the parameters to send to the API endpoint
for the round service view operation typically these are written to a http.Request
*/
type RoundServiceViewParams struct {

	/*ID*/
	ID string
	/*TournamentID*/
	TournamentID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the round service view params
func (o *RoundServiceViewParams) WithTimeout(timeout time.Duration) *RoundServiceViewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the round service view params
func (o *RoundServiceViewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the round service view params
func (o *RoundServiceViewParams) WithContext(ctx context.Context) *RoundServiceViewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the round service view params
func (o *RoundServiceViewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the round service view params
func (o *RoundServiceViewParams) WithHTTPClient(client *http.Client) *RoundServiceViewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the round service view params
func (o *RoundServiceViewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the round service view params
func (o *RoundServiceViewParams) WithID(id string) *RoundServiceViewParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the round service view params
func (o *RoundServiceViewParams) SetID(id string) {
	o.ID = id
}

// WithTournamentID adds the tournamentID to the round service view params
func (o *RoundServiceViewParams) WithTournamentID(tournamentID *string) *RoundServiceViewParams {
	o.SetTournamentID(tournamentID)
	return o
}

// SetTournamentID adds the tournamentId to the round service view params
func (o *RoundServiceViewParams) SetTournamentID(tournamentID *string) {
	o.TournamentID = tournamentID
}

// WriteToRequest writes these params to a swagger request
func (o *RoundServiceViewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.TournamentID != nil {

		// query param tournamentId
		var qrTournamentID string
		if o.TournamentID != nil {
			qrTournamentID = *o.TournamentID
		}
		qTournamentID := qrTournamentID
		if qTournamentID != "" {
			if err := r.SetQueryParam("tournamentId", qTournamentID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
