// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// RoundServiceViewReader is a Reader for the RoundServiceView structure.
type RoundServiceViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoundServiceViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoundServiceViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRoundServiceViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRoundServiceViewOK creates a RoundServiceViewOK with default headers values
func NewRoundServiceViewOK() *RoundServiceViewOK {
	return &RoundServiceViewOK{}
}

/*RoundServiceViewOK handles this case with default header values.

A successful response.
*/
type RoundServiceViewOK struct {
	Payload *models.APIRoundResponse
}

func (o *RoundServiceViewOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/round/{id}][%d] roundServiceViewOK  %+v", 200, o.Payload)
}

func (o *RoundServiceViewOK) GetPayload() *models.APIRoundResponse {
	return o.Payload
}

func (o *RoundServiceViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRoundResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRoundServiceViewDefault creates a RoundServiceViewDefault with default headers values
func NewRoundServiceViewDefault(code int) *RoundServiceViewDefault {
	return &RoundServiceViewDefault{
		_statusCode: code,
	}
}

/*RoundServiceViewDefault handles this case with default header values.

An unexpected error response.
*/
type RoundServiceViewDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the round service view default response
func (o *RoundServiceViewDefault) Code() int {
	return o._statusCode
}

func (o *RoundServiceViewDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/round/{id}][%d] RoundService_View default  %+v", o._statusCode, o.Payload)
}

func (o *RoundServiceViewDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *RoundServiceViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
