// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// SeriesServiceComputeReader is a Reader for the SeriesServiceCompute structure.
type SeriesServiceComputeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SeriesServiceComputeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSeriesServiceComputeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSeriesServiceComputeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSeriesServiceComputeOK creates a SeriesServiceComputeOK with default headers values
func NewSeriesServiceComputeOK() *SeriesServiceComputeOK {
	return &SeriesServiceComputeOK{}
}

/*SeriesServiceComputeOK handles this case with default header values.

A successful response.
*/
type SeriesServiceComputeOK struct {
	Payload *models.APISeriesResponse
}

func (o *SeriesServiceComputeOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/series/compute][%d] seriesServiceComputeOK  %+v", 200, o.Payload)
}

func (o *SeriesServiceComputeOK) GetPayload() *models.APISeriesResponse {
	return o.Payload
}

func (o *SeriesServiceComputeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APISeriesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSeriesServiceComputeDefault creates a SeriesServiceComputeDefault with default headers values
func NewSeriesServiceComputeDefault(code int) *SeriesServiceComputeDefault {
	return &SeriesServiceComputeDefault{
		_statusCode: code,
	}
}

/*SeriesServiceComputeDefault handles this case with default header values.

An unexpected error response.
*/
type SeriesServiceComputeDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the series service compute default response
func (o *SeriesServiceComputeDefault) Code() int {
	return o._statusCode
}

func (o *SeriesServiceComputeDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/series/compute][%d] SeriesService_Compute default  %+v", o._statusCode, o.Payload)
}

func (o *SeriesServiceComputeDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *SeriesServiceComputeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
