// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewSeriesServiceComputeParams creates a new SeriesServiceComputeParams object
// with the default values initialized.
func NewSeriesServiceComputeParams() *SeriesServiceComputeParams {
	var ()
	return &SeriesServiceComputeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSeriesServiceComputeParamsWithTimeout creates a new SeriesServiceComputeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSeriesServiceComputeParamsWithTimeout(timeout time.Duration) *SeriesServiceComputeParams {
	var ()
	return &SeriesServiceComputeParams{

		timeout: timeout,
	}
}

// NewSeriesServiceComputeParamsWithContext creates a new SeriesServiceComputeParams object
// with the default values initialized, and the ability to set a context for a request
func NewSeriesServiceComputeParamsWithContext(ctx context.Context) *SeriesServiceComputeParams {
	var ()
	return &SeriesServiceComputeParams{

		Context: ctx,
	}
}

// NewSeriesServiceComputeParamsWithHTTPClient creates a new SeriesServiceComputeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSeriesServiceComputeParamsWithHTTPClient(client *http.Client) *SeriesServiceComputeParams {
	var ()
	return &SeriesServiceComputeParams{
		HTTPClient: client,
	}
}

/*SeriesServiceComputeParams contains all the parameters to send to the API endpoint
for the series service compute operation typically these are written to a http.Request
*/
type SeriesServiceComputeParams struct {

	/*Body*/
	Body *models.APIID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the series service compute params
func (o *SeriesServiceComputeParams) WithTimeout(timeout time.Duration) *SeriesServiceComputeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the series service compute params
func (o *SeriesServiceComputeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the series service compute params
func (o *SeriesServiceComputeParams) WithContext(ctx context.Context) *SeriesServiceComputeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the series service compute params
func (o *SeriesServiceComputeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the series service compute params
func (o *SeriesServiceComputeParams) WithHTTPClient(client *http.Client) *SeriesServiceComputeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the series service compute params
func (o *SeriesServiceComputeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the series service compute params
func (o *SeriesServiceComputeParams) WithBody(body *models.APIID) *SeriesServiceComputeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the series service compute params
func (o *SeriesServiceComputeParams) SetBody(body *models.APIID) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SeriesServiceComputeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
