// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewSeriesServiceQueryParams creates a new SeriesServiceQueryParams object
// with the default values initialized.
func NewSeriesServiceQueryParams() *SeriesServiceQueryParams {
	var ()
	return &SeriesServiceQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSeriesServiceQueryParamsWithTimeout creates a new SeriesServiceQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSeriesServiceQueryParamsWithTimeout(timeout time.Duration) *SeriesServiceQueryParams {
	var ()
	return &SeriesServiceQueryParams{

		timeout: timeout,
	}
}

// NewSeriesServiceQueryParamsWithContext creates a new SeriesServiceQueryParams object
// with the default values initialized, and the ability to set a context for a request
func NewSeriesServiceQueryParamsWithContext(ctx context.Context) *SeriesServiceQueryParams {
	var ()
	return &SeriesServiceQueryParams{

		Context: ctx,
	}
}

// NewSeriesServiceQueryParamsWithHTTPClient creates a new SeriesServiceQueryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSeriesServiceQueryParamsWithHTTPClient(client *http.Client) *SeriesServiceQueryParams {
	var ()
	return &SeriesServiceQueryParams{
		HTTPClient: client,
	}
}

/*SeriesServiceQueryParams contains all the parameters to send to the API endpoint
for the series service query operation typically these are written to a http.Request
*/
type SeriesServiceQueryParams struct {

	/*Body*/
	Body *models.APIQuery

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the series service query params
func (o *SeriesServiceQueryParams) WithTimeout(timeout time.Duration) *SeriesServiceQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the series service query params
func (o *SeriesServiceQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the series service query params
func (o *SeriesServiceQueryParams) WithContext(ctx context.Context) *SeriesServiceQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the series service query params
func (o *SeriesServiceQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the series service query params
func (o *SeriesServiceQueryParams) WithHTTPClient(client *http.Client) *SeriesServiceQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the series service query params
func (o *SeriesServiceQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the series service query params
func (o *SeriesServiceQueryParams) WithBody(body *models.APIQuery) *SeriesServiceQueryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the series service query params
func (o *SeriesServiceQueryParams) SetBody(body *models.APIQuery) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SeriesServiceQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
