// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// SeriesServiceViewReader is a Reader for the SeriesServiceView structure.
type SeriesServiceViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SeriesServiceViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSeriesServiceViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSeriesServiceViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSeriesServiceViewOK creates a SeriesServiceViewOK with default headers values
func NewSeriesServiceViewOK() *SeriesServiceViewOK {
	return &SeriesServiceViewOK{}
}

/*SeriesServiceViewOK handles this case with default header values.

A successful response.
*/
type SeriesServiceViewOK struct {
	Payload *models.APISeriesResponse
}

func (o *SeriesServiceViewOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/series/{id}][%d] seriesServiceViewOK  %+v", 200, o.Payload)
}

func (o *SeriesServiceViewOK) GetPayload() *models.APISeriesResponse {
	return o.Payload
}

func (o *SeriesServiceViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APISeriesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSeriesServiceViewDefault creates a SeriesServiceViewDefault with default headers values
func NewSeriesServiceViewDefault(code int) *SeriesServiceViewDefault {
	return &SeriesServiceViewDefault{
		_statusCode: code,
	}
}

/*SeriesServiceViewDefault handles this case with default header values.

An unexpected error response.
*/
type SeriesServiceViewDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the series service view default response
func (o *SeriesServiceViewDefault) Code() int {
	return o._statusCode
}

func (o *SeriesServiceViewDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/series/{id}][%d] SeriesService_View default  %+v", o._statusCode, o.Payload)
}

func (o *SeriesServiceViewDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *SeriesServiceViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
