// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// StageSingleEliminationServiceComputeReader is a Reader for the StageSingleEliminationServiceCompute structure.
type StageSingleEliminationServiceComputeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StageSingleEliminationServiceComputeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStageSingleEliminationServiceComputeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStageSingleEliminationServiceComputeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStageSingleEliminationServiceComputeOK creates a StageSingleEliminationServiceComputeOK with default headers values
func NewStageSingleEliminationServiceComputeOK() *StageSingleEliminationServiceComputeOK {
	return &StageSingleEliminationServiceComputeOK{}
}

/*StageSingleEliminationServiceComputeOK handles this case with default header values.

A successful response.
*/
type StageSingleEliminationServiceComputeOK struct {
	Payload *models.APIStageSingleEliminationResponse
}

func (o *StageSingleEliminationServiceComputeOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/stage/se/compute][%d] stageSingleEliminationServiceComputeOK  %+v", 200, o.Payload)
}

func (o *StageSingleEliminationServiceComputeOK) GetPayload() *models.APIStageSingleEliminationResponse {
	return o.Payload
}

func (o *StageSingleEliminationServiceComputeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStageSingleEliminationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStageSingleEliminationServiceComputeDefault creates a StageSingleEliminationServiceComputeDefault with default headers values
func NewStageSingleEliminationServiceComputeDefault(code int) *StageSingleEliminationServiceComputeDefault {
	return &StageSingleEliminationServiceComputeDefault{
		_statusCode: code,
	}
}

/*StageSingleEliminationServiceComputeDefault handles this case with default header values.

An unexpected error response.
*/
type StageSingleEliminationServiceComputeDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the stage single elimination service compute default response
func (o *StageSingleEliminationServiceComputeDefault) Code() int {
	return o._statusCode
}

func (o *StageSingleEliminationServiceComputeDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/stage/se/compute][%d] StageSingleEliminationService_Compute default  %+v", o._statusCode, o.Payload)
}

func (o *StageSingleEliminationServiceComputeDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *StageSingleEliminationServiceComputeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
