// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// StageRoundRobinServiceComputeReader is a Reader for the StageRoundRobinServiceCompute structure.
type StageRoundRobinServiceComputeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StageRoundRobinServiceComputeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStageRoundRobinServiceComputeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStageRoundRobinServiceComputeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStageRoundRobinServiceComputeOK creates a StageRoundRobinServiceComputeOK with default headers values
func NewStageRoundRobinServiceComputeOK() *StageRoundRobinServiceComputeOK {
	return &StageRoundRobinServiceComputeOK{}
}

/*StageRoundRobinServiceComputeOK handles this case with default header values.

A successful response.
*/
type StageRoundRobinServiceComputeOK struct {
	Payload *models.APIStageRoundRobinResponse
}

func (o *StageRoundRobinServiceComputeOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/stage/rr/compute][%d] stageRoundRobinServiceComputeOK  %+v", 200, o.Payload)
}

func (o *StageRoundRobinServiceComputeOK) GetPayload() *models.APIStageRoundRobinResponse {
	return o.Payload
}

func (o *StageRoundRobinServiceComputeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStageRoundRobinResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStageRoundRobinServiceComputeDefault creates a StageRoundRobinServiceComputeDefault with default headers values
func NewStageRoundRobinServiceComputeDefault(code int) *StageRoundRobinServiceComputeDefault {
	return &StageRoundRobinServiceComputeDefault{
		_statusCode: code,
	}
}

/*StageRoundRobinServiceComputeDefault handles this case with default header values.

An unexpected error response.
*/
type StageRoundRobinServiceComputeDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the stage round robin service compute default response
func (o *StageRoundRobinServiceComputeDefault) Code() int {
	return o._statusCode
}

func (o *StageRoundRobinServiceComputeDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/stage/rr/compute][%d] StageRoundRobinService_Compute default  %+v", o._statusCode, o.Payload)
}

func (o *StageRoundRobinServiceComputeDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *StageRoundRobinServiceComputeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
