// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewStageSingleEliminationServiceComputeParams creates a new StageSingleEliminationServiceComputeParams object
// with the default values initialized.
func NewStageSingleEliminationServiceComputeParams() *StageSingleEliminationServiceComputeParams {
	var ()
	return &StageSingleEliminationServiceComputeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStageSingleEliminationServiceComputeParamsWithTimeout creates a new StageSingleEliminationServiceComputeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStageSingleEliminationServiceComputeParamsWithTimeout(timeout time.Duration) *StageSingleEliminationServiceComputeParams {
	var ()
	return &StageSingleEliminationServiceComputeParams{

		timeout: timeout,
	}
}

// NewStageSingleEliminationServiceComputeParamsWithContext creates a new StageSingleEliminationServiceComputeParams object
// with the default values initialized, and the ability to set a context for a request
func NewStageSingleEliminationServiceComputeParamsWithContext(ctx context.Context) *StageSingleEliminationServiceComputeParams {
	var ()
	return &StageSingleEliminationServiceComputeParams{

		Context: ctx,
	}
}

// NewStageSingleEliminationServiceComputeParamsWithHTTPClient creates a new StageSingleEliminationServiceComputeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStageSingleEliminationServiceComputeParamsWithHTTPClient(client *http.Client) *StageSingleEliminationServiceComputeParams {
	var ()
	return &StageSingleEliminationServiceComputeParams{
		HTTPClient: client,
	}
}

/*StageSingleEliminationServiceComputeParams contains all the parameters to send to the API endpoint
for the stage single elimination service compute operation typically these are written to a http.Request
*/
type StageSingleEliminationServiceComputeParams struct {

	/*Body*/
	Body *models.APIID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) WithTimeout(timeout time.Duration) *StageSingleEliminationServiceComputeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) WithContext(ctx context.Context) *StageSingleEliminationServiceComputeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) WithHTTPClient(client *http.Client) *StageSingleEliminationServiceComputeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) WithBody(body *models.APIID) *StageSingleEliminationServiceComputeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the stage single elimination service compute params
func (o *StageSingleEliminationServiceComputeParams) SetBody(body *models.APIID) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *StageSingleEliminationServiceComputeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
