// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewStageRoundRobinServiceQueryParams creates a new StageRoundRobinServiceQueryParams object
// with the default values initialized.
func NewStageRoundRobinServiceQueryParams() *StageRoundRobinServiceQueryParams {
	var ()
	return &StageRoundRobinServiceQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStageRoundRobinServiceQueryParamsWithTimeout creates a new StageRoundRobinServiceQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStageRoundRobinServiceQueryParamsWithTimeout(timeout time.Duration) *StageRoundRobinServiceQueryParams {
	var ()
	return &StageRoundRobinServiceQueryParams{

		timeout: timeout,
	}
}

// NewStageRoundRobinServiceQueryParamsWithContext creates a new StageRoundRobinServiceQueryParams object
// with the default values initialized, and the ability to set a context for a request
func NewStageRoundRobinServiceQueryParamsWithContext(ctx context.Context) *StageRoundRobinServiceQueryParams {
	var ()
	return &StageRoundRobinServiceQueryParams{

		Context: ctx,
	}
}

// NewStageRoundRobinServiceQueryParamsWithHTTPClient creates a new StageRoundRobinServiceQueryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStageRoundRobinServiceQueryParamsWithHTTPClient(client *http.Client) *StageRoundRobinServiceQueryParams {
	var ()
	return &StageRoundRobinServiceQueryParams{
		HTTPClient: client,
	}
}

/*StageRoundRobinServiceQueryParams contains all the parameters to send to the API endpoint
for the stage round robin service query operation typically these are written to a http.Request
*/
type StageRoundRobinServiceQueryParams struct {

	/*Body*/
	Body *models.APIQuery

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) WithTimeout(timeout time.Duration) *StageRoundRobinServiceQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) WithContext(ctx context.Context) *StageRoundRobinServiceQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) WithHTTPClient(client *http.Client) *StageRoundRobinServiceQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) WithBody(body *models.APIQuery) *StageRoundRobinServiceQueryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the stage round robin service query params
func (o *StageRoundRobinServiceQueryParams) SetBody(body *models.APIQuery) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *StageRoundRobinServiceQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
