// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewStageSingleEliminationServiceUpdateParams creates a new StageSingleEliminationServiceUpdateParams object
// with the default values initialized.
func NewStageSingleEliminationServiceUpdateParams() *StageSingleEliminationServiceUpdateParams {
	var ()
	return &StageSingleEliminationServiceUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStageSingleEliminationServiceUpdateParamsWithTimeout creates a new StageSingleEliminationServiceUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStageSingleEliminationServiceUpdateParamsWithTimeout(timeout time.Duration) *StageSingleEliminationServiceUpdateParams {
	var ()
	return &StageSingleEliminationServiceUpdateParams{

		timeout: timeout,
	}
}

// NewStageSingleEliminationServiceUpdateParamsWithContext creates a new StageSingleEliminationServiceUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewStageSingleEliminationServiceUpdateParamsWithContext(ctx context.Context) *StageSingleEliminationServiceUpdateParams {
	var ()
	return &StageSingleEliminationServiceUpdateParams{

		Context: ctx,
	}
}

// NewStageSingleEliminationServiceUpdateParamsWithHTTPClient creates a new StageSingleEliminationServiceUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStageSingleEliminationServiceUpdateParamsWithHTTPClient(client *http.Client) *StageSingleEliminationServiceUpdateParams {
	var ()
	return &StageSingleEliminationServiceUpdateParams{
		HTTPClient: client,
	}
}

/*StageSingleEliminationServiceUpdateParams contains all the parameters to send to the API endpoint
for the stage single elimination service update operation typically these are written to a http.Request
*/
type StageSingleEliminationServiceUpdateParams struct {

	/*Body*/
	Body *models.APIStageSingleEliminationRequestBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) WithTimeout(timeout time.Duration) *StageSingleEliminationServiceUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) WithContext(ctx context.Context) *StageSingleEliminationServiceUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) WithHTTPClient(client *http.Client) *StageSingleEliminationServiceUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) WithBody(body *models.APIStageSingleEliminationRequestBody) *StageSingleEliminationServiceUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) SetBody(body *models.APIStageSingleEliminationRequestBody) {
	o.Body = body
}

// WithID adds the id to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) WithID(id string) *StageSingleEliminationServiceUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the stage single elimination service update params
func (o *StageSingleEliminationServiceUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StageSingleEliminationServiceUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
