// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// StageSingleEliminationServiceDeleteReader is a Reader for the StageSingleEliminationServiceDelete structure.
type StageSingleEliminationServiceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StageSingleEliminationServiceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStageSingleEliminationServiceDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStageSingleEliminationServiceDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStageSingleEliminationServiceDeleteOK creates a StageSingleEliminationServiceDeleteOK with default headers values
func NewStageSingleEliminationServiceDeleteOK() *StageSingleEliminationServiceDeleteOK {
	return &StageSingleEliminationServiceDeleteOK{}
}

/*StageSingleEliminationServiceDeleteOK handles this case with default header values.

A successful response.
*/
type StageSingleEliminationServiceDeleteOK struct {
	Payload models.APIEmpty
}

func (o *StageSingleEliminationServiceDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/stage/se/{id}][%d] stageSingleEliminationServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *StageSingleEliminationServiceDeleteOK) GetPayload() models.APIEmpty {
	return o.Payload
}

func (o *StageSingleEliminationServiceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStageSingleEliminationServiceDeleteDefault creates a StageSingleEliminationServiceDeleteDefault with default headers values
func NewStageSingleEliminationServiceDeleteDefault(code int) *StageSingleEliminationServiceDeleteDefault {
	return &StageSingleEliminationServiceDeleteDefault{
		_statusCode: code,
	}
}

/*StageSingleEliminationServiceDeleteDefault handles this case with default header values.

An unexpected error response.
*/
type StageSingleEliminationServiceDeleteDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the stage single elimination service delete default response
func (o *StageSingleEliminationServiceDeleteDefault) Code() int {
	return o._statusCode
}

func (o *StageSingleEliminationServiceDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/stage/se/{id}][%d] StageSingleEliminationService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *StageSingleEliminationServiceDeleteDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *StageSingleEliminationServiceDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
