// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// NewTournamentServiceQueryParams creates a new TournamentServiceQueryParams object
// with the default values initialized.
func NewTournamentServiceQueryParams() *TournamentServiceQueryParams {
	var ()
	return &TournamentServiceQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTournamentServiceQueryParamsWithTimeout creates a new TournamentServiceQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTournamentServiceQueryParamsWithTimeout(timeout time.Duration) *TournamentServiceQueryParams {
	var ()
	return &TournamentServiceQueryParams{

		timeout: timeout,
	}
}

// NewTournamentServiceQueryParamsWithContext creates a new TournamentServiceQueryParams object
// with the default values initialized, and the ability to set a context for a request
func NewTournamentServiceQueryParamsWithContext(ctx context.Context) *TournamentServiceQueryParams {
	var ()
	return &TournamentServiceQueryParams{

		Context: ctx,
	}
}

// NewTournamentServiceQueryParamsWithHTTPClient creates a new TournamentServiceQueryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTournamentServiceQueryParamsWithHTTPClient(client *http.Client) *TournamentServiceQueryParams {
	var ()
	return &TournamentServiceQueryParams{
		HTTPClient: client,
	}
}

/*TournamentServiceQueryParams contains all the parameters to send to the API endpoint
for the tournament service query operation typically these are written to a http.Request
*/
type TournamentServiceQueryParams struct {

	/*Body*/
	Body *models.APIQuery

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tournament service query params
func (o *TournamentServiceQueryParams) WithTimeout(timeout time.Duration) *TournamentServiceQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tournament service query params
func (o *TournamentServiceQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tournament service query params
func (o *TournamentServiceQueryParams) WithContext(ctx context.Context) *TournamentServiceQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tournament service query params
func (o *TournamentServiceQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tournament service query params
func (o *TournamentServiceQueryParams) WithHTTPClient(client *http.Client) *TournamentServiceQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tournament service query params
func (o *TournamentServiceQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the tournament service query params
func (o *TournamentServiceQueryParams) WithBody(body *models.APIQuery) *TournamentServiceQueryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the tournament service query params
func (o *TournamentServiceQueryParams) SetBody(body *models.APIQuery) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TournamentServiceQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
