// Code generated by go-swagger; DO NOT EDIT.

package utl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owenmonagan/toureasy-sdk-go/models"
)

// UtilityServiceHealthReader is a Reader for the UtilityServiceHealth structure.
type UtilityServiceHealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UtilityServiceHealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUtilityServiceHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUtilityServiceHealthDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUtilityServiceHealthOK creates a UtilityServiceHealthOK with default headers values
func NewUtilityServiceHealthOK() *UtilityServiceHealthOK {
	return &UtilityServiceHealthOK{}
}

/*UtilityServiceHealthOK handles this case with default header values.

A successful response.
*/
type UtilityServiceHealthOK struct {
	Payload models.APIEmpty
}

func (o *UtilityServiceHealthOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/utl/health][%d] utilityServiceHealthOK  %+v", 200, o.Payload)
}

func (o *UtilityServiceHealthOK) GetPayload() models.APIEmpty {
	return o.Payload
}

func (o *UtilityServiceHealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUtilityServiceHealthDefault creates a UtilityServiceHealthDefault with default headers values
func NewUtilityServiceHealthDefault(code int) *UtilityServiceHealthDefault {
	return &UtilityServiceHealthDefault{
		_statusCode: code,
	}
}

/*UtilityServiceHealthDefault handles this case with default header values.

An unexpected error response.
*/
type UtilityServiceHealthDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the utility service health default response
func (o *UtilityServiceHealthDefault) Code() int {
	return o._statusCode
}

func (o *UtilityServiceHealthDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/utl/health][%d] UtilityService_Health default  %+v", o._statusCode, o.Payload)
}

func (o *UtilityServiceHealthDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *UtilityServiceHealthDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
