// Code generated by go-swagger; DO NOT EDIT.

package stage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new stage API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for stage API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	StageRoundRobinServiceDelete(params *StageRoundRobinServiceDeleteParams) (*StageRoundRobinServiceDeleteOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  StageRoundRobinServiceDelete deletes a round robin stage

  Delete a round robin stage when given an id
*/
func (a *Client) StageRoundRobinServiceDelete(params *StageRoundRobinServiceDeleteParams) (*StageRoundRobinServiceDeleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStageRoundRobinServiceDeleteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "StageRoundRobinService_Delete",
		Method:             "DELETE",
		PathPattern:        "/api/v1/stage/roundrobin/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StageRoundRobinServiceDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StageRoundRobinServiceDeleteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*StageRoundRobinServiceDeleteDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
