// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIAllReferences api all references
//
// swagger:model apiAllReferences
type APIAllReferences struct {

	// game ids
	GameIds []*APIEdge `json:"gameIds"`

	// group ids
	GroupIds []*APIEdge `json:"groupIds"`

	// round ids
	RoundIds []*APIEdge `json:"roundIds"`

	// series ids
	SeriesIds []*APIEdge `json:"seriesIds"`

	// stage rr ids
	StageRrIds []*APIEdge `json:"stageRrIds"`

	// stage se ids
	StageSeIds []*APIEdge `json:"stageSeIds"`

	// tournament ids
	TournamentIds []*APIEdge `json:"tournamentIds"`
}

// Validate validates this api all references
func (m *APIAllReferences) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGameIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoundIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeriesIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStageRrIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStageSeIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTournamentIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIAllReferences) validateGameIds(formats strfmt.Registry) error {

	if swag.IsZero(m.GameIds) { // not required
		return nil
	}

	for i := 0; i < len(m.GameIds); i++ {
		if swag.IsZero(m.GameIds[i]) { // not required
			continue
		}

		if m.GameIds[i] != nil {
			if err := m.GameIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("gameIds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIAllReferences) validateGroupIds(formats strfmt.Registry) error {

	if swag.IsZero(m.GroupIds) { // not required
		return nil
	}

	for i := 0; i < len(m.GroupIds); i++ {
		if swag.IsZero(m.GroupIds[i]) { // not required
			continue
		}

		if m.GroupIds[i] != nil {
			if err := m.GroupIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("groupIds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIAllReferences) validateRoundIds(formats strfmt.Registry) error {

	if swag.IsZero(m.RoundIds) { // not required
		return nil
	}

	for i := 0; i < len(m.RoundIds); i++ {
		if swag.IsZero(m.RoundIds[i]) { // not required
			continue
		}

		if m.RoundIds[i] != nil {
			if err := m.RoundIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("roundIds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIAllReferences) validateSeriesIds(formats strfmt.Registry) error {

	if swag.IsZero(m.SeriesIds) { // not required
		return nil
	}

	for i := 0; i < len(m.SeriesIds); i++ {
		if swag.IsZero(m.SeriesIds[i]) { // not required
			continue
		}

		if m.SeriesIds[i] != nil {
			if err := m.SeriesIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("seriesIds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIAllReferences) validateStageRrIds(formats strfmt.Registry) error {

	if swag.IsZero(m.StageRrIds) { // not required
		return nil
	}

	for i := 0; i < len(m.StageRrIds); i++ {
		if swag.IsZero(m.StageRrIds[i]) { // not required
			continue
		}

		if m.StageRrIds[i] != nil {
			if err := m.StageRrIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stageRrIds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIAllReferences) validateStageSeIds(formats strfmt.Registry) error {

	if swag.IsZero(m.StageSeIds) { // not required
		return nil
	}

	for i := 0; i < len(m.StageSeIds); i++ {
		if swag.IsZero(m.StageSeIds[i]) { // not required
			continue
		}

		if m.StageSeIds[i] != nil {
			if err := m.StageSeIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stageSeIds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIAllReferences) validateTournamentIds(formats strfmt.Registry) error {

	if swag.IsZero(m.TournamentIds) { // not required
		return nil
	}

	for i := 0; i < len(m.TournamentIds); i++ {
		if swag.IsZero(m.TournamentIds[i]) { // not required
			continue
		}

		if m.TournamentIds[i] != nil {
			if err := m.TournamentIds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tournamentIds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIAllReferences) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAllReferences) UnmarshalBinary(b []byte) error {
	var res APIAllReferences
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
