// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIFormatSeriesRequestBody api format series request body
//
// swagger:model apiFormatSeriesRequestBody
type APIFormatSeriesRequestBody struct {

	// has format
	HasFormat *APIAllReferences `json:"hasFormat,omitempty"`

	// object
	Object *APIFormatSeries `json:"object,omitempty"`

	// tournament Id
	TournamentID string `json:"tournamentId,omitempty"`
}

// Validate validates this api format series request body
func (m *APIFormatSeriesRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHasFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIFormatSeriesRequestBody) validateHasFormat(formats strfmt.Registry) error {

	if swag.IsZero(m.HasFormat) { // not required
		return nil
	}

	if m.HasFormat != nil {
		if err := m.HasFormat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("hasFormat")
			}
			return err
		}
	}

	return nil
}

func (m *APIFormatSeriesRequestBody) validateObject(formats strfmt.Registry) error {

	if swag.IsZero(m.Object) { // not required
		return nil
	}

	if m.Object != nil {
		if err := m.Object.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("object")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIFormatSeriesRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIFormatSeriesRequestBody) UnmarshalBinary(b []byte) error {
	var res APIFormatSeriesRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
