// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APISequence api sequence
//
// swagger:model apiSequence
type APISequence struct {

	// from
	From *APIReference `json:"from,omitempty"`

	// game
	Game int32 `json:"game,omitempty"`

	// group
	Group int32 `json:"group,omitempty"`

	// round
	Round int32 `json:"round,omitempty"`

	// series
	Series int32 `json:"series,omitempty"`

	// stage
	Stage int32 `json:"stage,omitempty"`
}

// Validate validates this api sequence
func (m *APISequence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APISequence) validateFrom(formats strfmt.Registry) error {

	if swag.IsZero(m.From) { // not required
		return nil
	}

	if m.From != nil {
		if err := m.From.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("from")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APISequence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APISequence) UnmarshalBinary(b []byte) error {
	var res APISequence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
