// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIFormatScoreRequestBody api format score request body
//
// swagger:model apiFormatScoreRequestBody
type APIFormatScoreRequestBody struct {

	// has format
	HasFormat []*APIReference `json:"hasFormat"`

	// id
	ID string `json:"id,omitempty"`

	// object
	Object *APIFormatScore `json:"object,omitempty"`

	// tournament Id
	TournamentID string `json:"tournamentId,omitempty"`
}

// Validate validates this api format score request body
func (m *APIFormatScoreRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHasFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIFormatScoreRequestBody) validateHasFormat(formats strfmt.Registry) error {

	if swag.IsZero(m.HasFormat) { // not required
		return nil
	}

	for i := 0; i < len(m.HasFormat); i++ {
		if swag.IsZero(m.HasFormat[i]) { // not required
			continue
		}

		if m.HasFormat[i] != nil {
			if err := m.HasFormat[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hasFormat" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIFormatScoreRequestBody) validateObject(formats strfmt.Registry) error {

	if swag.IsZero(m.Object) { // not required
		return nil
	}

	if m.Object != nil {
		if err := m.Object.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("object")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIFormatScoreRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIFormatScoreRequestBody) UnmarshalBinary(b []byte) error {
	var res APIFormatScoreRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
